# Generated by Django 3.1.6 on 2024-09-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('register', models.CharField(default=0, max_length=20, unique=True)),
                ('department', models.CharField(max_length=20)),
                ('dob', models.DateField()),
            ],
        ),
    ]
